### ISSUE TITLE
是否可以执行js文件中的某个方法

### ISSUE THREAD

**Issue by bjhexn** [taoweiji/quickjs-android#12]
需求： 想执行js文件中的某个方法。

例如先load某个js文件，在需要执行的时候在调用js方法。

**Comment by taoweiji** [comment]
可以了

**Comment by bjhexn** [comment]
getSystemInfo( {
                  success(e) {
                         console.log("-----getSystemInfo----",JSON.stringify(e))
                })


有这样的 js方法改如何调用呢 js 代码

getSystemInfo('{\"diskSpaceFree\":\"5575598080\",\"status\":\"0\",\"os\":\"android\",\"mac\":\"02:15:B2:00:00:00\",\"statusBarHeight\":48,\"model\":\"Android SDK built for x86\",\"message\":\"成功\",\"deviceId\":\"c7633a624aed1d09\",\"diskSpaceTotal\":\"6240665600\",\"memoryTotal\":\"2090921984\",\"osVersion\":\"10\",\"memoryFree\":\"1087508480\",\"titleBarHeight\":96}')


在getSystemInfo 中传入一个JSON

**Comment by bjhexn** [comment]
下午调试发现，执行js 只能在主线程中执行。

**Comment by taoweiji** [comment]
这个方法可以创建非主线程的线程池
QuickJS quickJS = QuickJS. createRuntimeWithEventQueue();

**Comment by taoweiji** [comment]
因为quickjs所有的方法都必须执行在同一个线程

**Comment by bjhexn** [comment]
> 因为quickjs所有的方法都必须执行在同一个线程

OK 了解。

**Comment by zeropercenthappy** [comment]
请问相关场景的文档或者使用方法有吗？
我尝试在JsContext的executeScript方法中测试，source入参是相应的调用js方法，fileName中是js文件的路径，
但是看起来好像js文件没有load成功？调用时一直时undefined异常。
对应的场景可以说一下怎么使用的吗？

**Comment by zeropercenthappy** [comment]
> 请问相关场景的文档或者使用方法有吗？ 我尝试在JsContext的executeScript方法中测试，source入参是相应的调用js方法，fileName中是js文件的路径， 但是看起来好像js文件没有load成功？调用时一直时undefined异常。 对应的场景可以说一下怎么使用的吗？

没事了，之前不太了解js，查了一下ES6的导出导入功能之后用ES6Module实现了。

**Comment by muziling** [comment]
@taoweiji  
需求： 想执行js文件中的某个方法。

例如先load某个js文件，在需要执行的时候在调用js方法。


能提供个示例代码吗？ 看了文档和sample代码不知道怎么用。
