### ISSUE TITLE
这个依赖区分 armeabi-v7a  和 arm64-v8a吗？还是都支持？

### ISSUE THREAD

**Issue by peienliudao** [taoweiji/quickjs-android#19]
大家好，这个依赖（implementation 'io.github.taoweiji.quickjs:quickjs-android:1.+'）区分 armeabi-v7a  和 arm64-v8a吗？还是都支持？

是否针对不同的架构（armeabi-v7a  和 arm64-v8a）要有不同的依赖？

**Comment by taoweiji** [comment]
都支持

**Comment by peienliudao** [comment]
好的，谢谢！！
